export interface Country {
    flag: string;
    code: string;
    name: string;
    nameEn: string;
}

export const countries: Country[] = [
    // Europe
    { flag: '🇨🇭', code: '+41', name: 'Suisse', nameEn: 'Switzerland' },
    { flag: '🇫🇷', code: '+33', name: 'France', nameEn: 'France' },
    { flag: '🇧🇪', code: '+32', name: 'Belgique', nameEn: 'Belgium' },
    { flag: '🇩🇪', code: '+49', name: 'Allemagne', nameEn: 'Germany' },
    { flag: '🇮🇹', code: '+39', name: 'Italie', nameEn: 'Italy' },
    { flag: '🇪🇸', code: '+34', name: 'Espagne', nameEn: 'Spain' },
    { flag: '🇵🇹', code: '+351', name: 'Portugal', nameEn: 'Portugal' },
    { flag: '🇳🇱', code: '+31', name: 'Pays-Bas', nameEn: 'Netherlands' },
    { flag: '🇦🇹', code: '+43', name: 'Autriche', nameEn: 'Austria' },
    { flag: '🇸🇪', code: '+46', name: 'Suède', nameEn: 'Sweden' },
    { flag: '🇳🇴', code: '+47', name: 'Norvège', nameEn: 'Norway' },
    { flag: '🇩🇰', code: '+45', name: 'Danemark', nameEn: 'Denmark' },
    { flag: '🇫🇮', code: '+358', name: 'Finlande', nameEn: 'Finland' },
    { flag: '🇵🇱', code: '+48', name: 'Pologne', nameEn: 'Poland' },
    { flag: '🇨🇿', code: '+420', name: 'République tchèque', nameEn: 'Czech Republic' },
    { flag: '🇭🇺', code: '+36', name: 'Hongrie', nameEn: 'Hungary' },
    { flag: '🇷🇴', code: '+40', name: 'Roumanie', nameEn: 'Romania' },
    { flag: '🇧🇬', code: '+359', name: 'Bulgarie', nameEn: 'Bulgaria' },
    { flag: '🇭🇷', code: '+385', name: 'Croatie', nameEn: 'Croatia' },
    { flag: '🇸🇰', code: '+421', name: 'Slovaquie', nameEn: 'Slovakia' },
    { flag: '🇸🇮', code: '+386', name: 'Slovénie', nameEn: 'Slovenia' },
    { flag: '🇪🇪', code: '+372', name: 'Estonie', nameEn: 'Estonia' },
    { flag: '🇱🇻', code: '+371', name: 'Lettonie', nameEn: 'Latvia' },
    { flag: '🇱🇹', code: '+370', name: 'Lituanie', nameEn: 'Lithuania' },
    { flag: '🇬🇷', code: '+30', name: 'Grèce', nameEn: 'Greece' },
    { flag: '🇨🇾', code: '+357', name: 'Chypre', nameEn: 'Cyprus' },
    { flag: '🇲🇹', code: '+356', name: 'Malte', nameEn: 'Malta' },
    { flag: '🇮🇪', code: '+353', name: 'Irlande', nameEn: 'Ireland' },
    { flag: '🇬🇧', code: '+44', name: 'Royaume-Uni', nameEn: 'United Kingdom' },
    { flag: '🇮🇸', code: '+354', name: 'Islande', nameEn: 'Iceland' },
    { flag: '🇱🇺', code: '+352', name: 'Luxembourg', nameEn: 'Luxembourg' },
    { flag: '🇱🇮', code: '+423', name: 'Liechtenstein', nameEn: 'Liechtenstein' },
    { flag: '🇲🇨', code: '+377', name: 'Monaco', nameEn: 'Monaco' },
    { flag: '🇦🇩', code: '+376', name: 'Andorre', nameEn: 'Andorra' },
    { flag: '🇸🇲', code: '+378', name: 'Saint-Marin', nameEn: 'San Marino' },
    { flag: '🇻🇦', code: '+379', name: 'Vatican', nameEn: 'Vatican City' },

    // Amérique du Nord
    { flag: '🇺🇸', code: '+1', name: 'États-Unis', nameEn: 'United States' },
    { flag: '🇨🇦', code: '+1', name: 'Canada', nameEn: 'Canada' },
    { flag: '🇲🇽', code: '+52', name: 'Mexique', nameEn: 'Mexico' },

    // Amérique du Sud
    { flag: '🇧🇷', code: '+55', name: 'Brésil', nameEn: 'Brazil' },
    { flag: '🇦🇷', code: '+54', name: 'Argentine', nameEn: 'Argentina' },
    { flag: '🇨🇱', code: '+56', name: 'Chili', nameEn: 'Chile' },
    { flag: '🇨🇴', code: '+57', name: 'Colombie', nameEn: 'Colombia' },
    { flag: '🇵🇪', code: '+51', name: 'Pérou', nameEn: 'Peru' },
    { flag: '🇻🇪', code: '+58', name: 'Venezuela', nameEn: 'Venezuela' },
    { flag: '🇪🇨', code: '+593', name: 'Équateur', nameEn: 'Ecuador' },
    { flag: '🇧🇴', code: '+591', name: 'Bolivie', nameEn: 'Bolivia' },
    { flag: '🇵🇾', code: '+595', name: 'Paraguay', nameEn: 'Paraguay' },
    { flag: '🇺🇾', code: '+598', name: 'Uruguay', nameEn: 'Uruguay' },
    { flag: '🇬🇾', code: '+592', name: 'Guyana', nameEn: 'Guyana' },
    { flag: '🇸🇷', code: '+597', name: 'Suriname', nameEn: 'Suriname' },

    // Afrique
    { flag: '🇩🇿', code: '+213', name: 'Algérie', nameEn: 'Algeria' },
    { flag: '🇲🇦', code: '+212', name: 'Maroc', nameEn: 'Morocco' },
    { flag: '🇹🇳', code: '+216', name: 'Tunisie', nameEn: 'Tunisia' },
    { flag: '🇱🇾', code: '+218', name: 'Libye', nameEn: 'Libya' },
    { flag: '🇪🇬', code: '+20', name: 'Égypte', nameEn: 'Egypt' },
    { flag: '🇸🇩', code: '+249', name: 'Soudan', nameEn: 'Sudan' },
    { flag: '🇹🇩', code: '+235', name: 'Tchad', nameEn: 'Chad' },
    { flag: '🇳🇪', code: '+227', name: 'Niger', nameEn: 'Niger' },
    { flag: '🇲🇱', code: '+223', name: 'Mali', nameEn: 'Mali' },
    { flag: '🇧🇫', code: '+226', name: 'Burkina Faso', nameEn: 'Burkina Faso' },
    { flag: '🇨🇮', code: '+225', name: 'Côte d\'Ivoire', nameEn: 'Ivory Coast' },
    { flag: '🇬🇭', code: '+233', name: 'Ghana', nameEn: 'Ghana' },
    { flag: '🇹🇬', code: '+228', name: 'Togo', nameEn: 'Togo' },
    { flag: '🇧🇯', code: '+229', name: 'Bénin', nameEn: 'Benin' },
    { flag: '🇳🇬', code: '+234', name: 'Nigeria', nameEn: 'Nigeria' },
    { flag: '🇨🇲', code: '+237', name: 'Cameroun', nameEn: 'Cameroon' },
    { flag: '🇨🇫', code: '+236', name: 'République centrafricaine', nameEn: 'Central African Republic' },
    { flag: '🇹🇩', code: '+235', name: 'Tchad', nameEn: 'Chad' },
    { flag: '🇨🇬', code: '+242', name: 'République du Congo', nameEn: 'Republic of the Congo' },
    { flag: '🇨🇩', code: '+243', name: 'République démocratique du Congo', nameEn: 'Democratic Republic of the Congo' },
    { flag: '🇬🇦', code: '+241', name: 'Gabon', nameEn: 'Gabon' },
    { flag: '🇬🇶', code: '+240', name: 'Guinée équatoriale', nameEn: 'Equatorial Guinea' },
    { flag: '🇸🇹', code: '+239', name: 'Sao Tomé-et-Principe', nameEn: 'Sao Tome and Principe' },
    { flag: '🇦🇴', code: '+244', name: 'Angola', nameEn: 'Angola' },
    { flag: '🇿🇲', code: '+260', name: 'Zambie', nameEn: 'Zambia' },
    { flag: '🇿🇼', code: '+263', name: 'Zimbabwe', nameEn: 'Zimbabwe' },
    { flag: '🇧🇼', code: '+267', name: 'Botswana', nameEn: 'Botswana' },
    { flag: '🇳🇦', code: '+264', name: 'Namibie', nameEn: 'Namibia' },
    { flag: '🇿🇦', code: '+27', name: 'Afrique du Sud', nameEn: 'South Africa' },
    { flag: '🇱🇸', code: '+266', name: 'Lesotho', nameEn: 'Lesotho' },
    { flag: '🇸🇿', code: '+268', name: 'Eswatini', nameEn: 'Eswatini' },
    { flag: '🇲🇿', code: '+258', name: 'Mozambique', nameEn: 'Mozambique' },
    { flag: '🇲🇼', code: '+265', name: 'Malawi', nameEn: 'Malawi' },
    { flag: '🇹🇿', code: '+255', name: 'Tanzanie', nameEn: 'Tanzania' },
    { flag: '🇰🇪', code: '+254', name: 'Kenya', nameEn: 'Kenya' },
    { flag: '🇺🇬', code: '+256', name: 'Ouganda', nameEn: 'Uganda' },
    { flag: '🇷🇼', code: '+250', name: 'Rwanda', nameEn: 'Rwanda' },
    { flag: '🇧🇮', code: '+257', name: 'Burundi', nameEn: 'Burundi' },
    { flag: '🇪🇹', code: '+251', name: 'Éthiopie', nameEn: 'Ethiopia' },
    { flag: '🇸🇴', code: '+252', name: 'Somalie', nameEn: 'Somalia' },
    { flag: '🇩🇯', code: '+253', name: 'Djibouti', nameEn: 'Djibouti' },
    { flag: '🇪🇷', code: '+291', name: 'Érythrée', nameEn: 'Eritrea' },
    { flag: '🇸🇸', code: '+211', name: 'Soudan du Sud', nameEn: 'South Sudan' },

    // Asie
    { flag: '🇨🇳', code: '+86', name: 'Chine', nameEn: 'China' },
    { flag: '🇯🇵', code: '+81', name: 'Japon', nameEn: 'Japan' },
    { flag: '🇰🇷', code: '+82', name: 'Corée du Sud', nameEn: 'South Korea' },
    { flag: '🇰🇵', code: '+850', name: 'Corée du Nord', nameEn: 'North Korea' },
    { flag: '🇹🇼', code: '+886', name: 'Taïwan', nameEn: 'Taiwan' },
    { flag: '🇭🇰', code: '+852', name: 'Hong Kong', nameEn: 'Hong Kong' },
    { flag: '🇲🇴', code: '+853', name: 'Macao', nameEn: 'Macau' },
    { flag: '🇲🇳', code: '+976', name: 'Mongolie', nameEn: 'Mongolia' },
    { flag: '🇷🇺', code: '+7', name: 'Russie', nameEn: 'Russia' },
    { flag: '🇰🇿', code: '+7', name: 'Kazakhstan', nameEn: 'Kazakhstan' },
    { flag: '🇰🇬', code: '+996', name: 'Kirghizistan', nameEn: 'Kyrgyzstan' },
    { flag: '🇹🇯', code: '+992', name: 'Tadjikistan', nameEn: 'Tajikistan' },
    { flag: '🇹🇲', code: '+993', name: 'Turkménistan', nameEn: 'Turkmenistan' },
    { flag: '🇺🇿', code: '+998', name: 'Ouzbékistan', nameEn: 'Uzbekistan' },
    { flag: '🇦🇿', code: '+994', name: 'Azerbaïdjan', nameEn: 'Azerbaijan' },
    { flag: '🇬🇪', code: '+995', name: 'Géorgie', nameEn: 'Georgia' },
    { flag: '🇦🇲', code: '+374', name: 'Arménie', nameEn: 'Armenia' },
    { flag: '🇹🇷', code: '+90', name: 'Turquie', nameEn: 'Turkey' },
    { flag: '🇮🇷', code: '+98', name: 'Iran', nameEn: 'Iran' },
    { flag: '🇮🇶', code: '+964', name: 'Irak', nameEn: 'Iraq' },
    { flag: '🇸🇾', code: '+963', name: 'Syrie', nameEn: 'Syria' },
    { flag: '🇱🇧', code: '+961', name: 'Liban', nameEn: 'Lebanon' },
    { flag: '🇯🇴', code: '+962', name: 'Jordanie', nameEn: 'Jordan' },
    { flag: '🇮🇱', code: '+972', name: 'Israël', nameEn: 'Israel' },
    { flag: '🇵🇸', code: '+970', name: 'Palestine', nameEn: 'Palestine' },
    { flag: '🇸🇦', code: '+966', name: 'Arabie saoudite', nameEn: 'Saudi Arabia' },
    { flag: '🇰🇼', code: '+965', name: 'Koweït', nameEn: 'Kuwait' },
    { flag: '🇶🇦', code: '+974', name: 'Qatar', nameEn: 'Qatar' },
    { flag: '🇦🇪', code: '+971', name: 'Émirats arabes unis', nameEn: 'United Arab Emirates' },
    { flag: '🇧🇭', code: '+973', name: 'Bahreïn', nameEn: 'Bahrain' },
    { flag: '🇴🇲', code: '+968', name: 'Oman', nameEn: 'Oman' },
    { flag: '🇾🇪', code: '+967', name: 'Yémen', nameEn: 'Yemen' },
    { flag: '🇦🇫', code: '+93', name: 'Afghanistan', nameEn: 'Afghanistan' },
    { flag: '🇵🇰', code: '+92', name: 'Pakistan', nameEn: 'Pakistan' },
    { flag: '🇮🇳', code: '+91', name: 'Inde', nameEn: 'India' },
    { flag: '🇧🇩', code: '+880', name: 'Bangladesh', nameEn: 'Bangladesh' },
    { flag: '🇱🇰', code: '+94', name: 'Sri Lanka', nameEn: 'Sri Lanka' },
    { flag: '🇲🇻', code: '+960', name: 'Maldives', nameEn: 'Maldives' },
    { flag: '🇳🇵', code: '+977', name: 'Népal', nameEn: 'Nepal' },
    { flag: '🇧🇹', code: '+975', name: 'Bhoutan', nameEn: 'Bhutan' },
    { flag: '🇲🇲', code: '+95', name: 'Myanmar', nameEn: 'Myanmar' },
    { flag: '🇹🇭', code: '+66', name: 'Thaïlande', nameEn: 'Thailand' },
    { flag: '🇱🇦', code: '+856', name: 'Laos', nameEn: 'Laos' },
    { flag: '🇰🇭', code: '+855', name: 'Cambodge', nameEn: 'Cambodia' },
    { flag: '🇻🇳', code: '+84', name: 'Vietnam', nameEn: 'Vietnam' },
    { flag: '🇲🇾', code: '+60', name: 'Malaisie', nameEn: 'Malaysia' },
    { flag: '🇸🇬', code: '+65', name: 'Singapour', nameEn: 'Singapore' },
    { flag: '🇧🇳', code: '+673', name: 'Brunei', nameEn: 'Brunei' },
    { flag: '🇵🇭', code: '+63', name: 'Philippines', nameEn: 'Philippines' },
    { flag: '🇮🇩', code: '+62', name: 'Indonésie', nameEn: 'Indonesia' },
    { flag: '🇹🇱', code: '+670', name: 'Timor oriental', nameEn: 'East Timor' },

    // Océanie
    { flag: '🇦🇺', code: '+61', name: 'Australie', nameEn: 'Australia' },
    { flag: '🇳🇿', code: '+64', name: 'Nouvelle-Zélande', nameEn: 'New Zealand' },
    { flag: '🇵🇬', code: '+675', name: 'Papouasie-Nouvelle-Guinée', nameEn: 'Papua New Guinea' },
    { flag: '🇫🇯', code: '+679', name: 'Fidji', nameEn: 'Fiji' },
    { flag: '🇸🇧', code: '+677', name: 'Îles Salomon', nameEn: 'Solomon Islands' },
    { flag: '🇻🇺', code: '+678', name: 'Vanuatu', nameEn: 'Vanuatu' },
    { flag: '🇳🇨', code: '+687', name: 'Nouvelle-Calédonie', nameEn: 'New Caledonia' },
    { flag: '🇵🇫', code: '+689', name: 'Polynésie française', nameEn: 'French Polynesia' },

    // Caraïbes
    { flag: '🇨🇺', code: '+53', name: 'Cuba', nameEn: 'Cuba' },
    { flag: '🇯🇲', code: '+1876', name: 'Jamaïque', nameEn: 'Jamaica' },
    { flag: '🇭🇹', code: '+509', name: 'Haïti', nameEn: 'Haiti' },
    { flag: '🇩🇴', code: '+1809', name: 'République dominicaine', nameEn: 'Dominican Republic' },
    { flag: '🇵🇷', code: '+1787', name: 'Porto Rico', nameEn: 'Puerto Rico' },
    { flag: '🇧🇧', code: '+1246', name: 'Barbade', nameEn: 'Barbados' },
    { flag: '🇹🇹', code: '+1868', name: 'Trinité-et-Tobago', nameEn: 'Trinidad and Tobago' },
    { flag: '🇬🇩', code: '+1473', name: 'Grenade', nameEn: 'Grenada' },
    { flag: '🇱🇨', code: '+1758', name: 'Sainte-Lucie', nameEn: 'Saint Lucia' },
    { flag: '🇻🇨', code: '+1784', name: 'Saint-Vincent-et-les-Grenadines', nameEn: 'Saint Vincent and the Grenadines' },
    { flag: '🇦🇬', code: '+1268', name: 'Antigua-et-Barbuda', nameEn: 'Antigua and Barbuda' },
    { flag: '🇰🇳', code: '+1869', name: 'Saint-Kitts-et-Nevis', nameEn: 'Saint Kitts and Nevis' },
    { flag: '🇩🇲', code: '+1809', name: 'Dominique', nameEn: 'Dominica' },
    { flag: '🇧🇸', code: '+1242', name: 'Bahamas', nameEn: 'Bahamas' },
    { flag: '🇧🇿', code: '+501', name: 'Belize', nameEn: 'Belize' },
    { flag: '🇬🇹', code: '+502', name: 'Guatemala', nameEn: 'Guatemala' },
    { flag: '🇭🇳', code: '+504', name: 'Honduras', nameEn: 'Honduras' },
    { flag: '🇸🇻', code: '+503', name: 'El Salvador', nameEn: 'El Salvador' },
    { flag: '🇳🇮', code: '+505', name: 'Nicaragua', nameEn: 'Nicaragua' },
    { flag: '🇨🇷', code: '+506', name: 'Costa Rica', nameEn: 'Costa Rica' },
    { flag: '🇵🇦', code: '+507', name: 'Panama', nameEn: 'Panama' },
];

export default countries;
