name: Build Android APK
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'myApp/package-lock.json'
          
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-platform: '35'
          sdk-build-tools: '35.0.0'
          
      - name: Install dependencies
        run: |
          cd myApp
          npm install --legacy-peer-deps
          
      - name: Build Android APK and AAB
        run: |
          cd myApp/android
          chmod +x ./gradlew
          ./gradlew assembleRelease bundleRelease
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: myApp/android/app/build/outputs/apk/release/app-release.apk
          retention-days: 1
          compression-level: 9
          
      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: myApp/android/app/build/outputs/bundle/release/app-release.aab
          retention-days: 1
          compression-level: 9
          
      - name: Cleanup old artifacts
        run: |
          gh auth login --with-token ${{ secrets.GITHUB_TOKEN }}
          gh api repos/${{ github.repository }}/actions/artifacts | jq '.artifacts[] | .id' | xargs -I {} gh api -X DELETE repos/${{ github.repository }}/actions/artifacts/{}
